import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000';
type Report={id:number;report_type:string;category:string;description:string;location:string;people_affected:number;required_quantity:number;timestamp:string;evidence_status:string;evidence_source:string;evidence_note:string;evidence_observed_at:string|null;verification_status:string;is_synthetic:boolean};
type Relationship={id:number;report_a_id:number;report_b_id:number;relationship_type:string;similarity:number;reason:string;decision:string};
type Evidence={report_id:number;evidence_status:string;evidence_source:string;evidence_note:string;observed_at:string|null;age_minutes:number|null;freshness:string;human_review_required:boolean};
type Need={need_id:number;report_id:number;verified_quantity:number;unit:string;allocated_quantity:number;remaining_to_allocate:number;delivered_quantity:number;uncovered_quantity:number;coverage_percent:number};
type Resource={id:number;name:string;resource_type:string;unit:string;location:string;available_quantity:number;allocated_quantity:number;status:string;source:string;is_synthetic:boolean};
type Allocation={id:number;need_id:number;resource_id:number;allocated_quantity:number;delivered_quantity:number;remaining_quantity:number};
type Coverage={total_verified:number;total_delivered:number;total_uncovered:number;needs:Need[]};
type Audit={id:number;event_type:string;entity_type:string;entity_id:number;summary:string;created_at:string};
type Dashboard={report_count:number;unverified_report_count:number;pending_relationship_count:number;verified_need_count:number;uncovered_need_count:number;recent_audit:Audit[]};
type QueueReport={id:number;report_type:string;category:string;description:string;location:string;people_affected:number;required_quantity:number;timestamp:string;verification_status:string;evidence:{status:string;source:string;note:string|null;observed_at:string|null;freshness:string;human_review_required:boolean}};
type QueueItem={relationship_id:number;relationship_type:string;similarity:number;reason:string;decision_guidance:string;report_a:QueueReport;report_b:QueueReport};
type Queue={count:number;items:QueueItem[]};
function App(){
 const [reports,setReports]=useState<Report[]>([]),[rels,setRels]=useState<Relationship[]>([]),[coverage,setCoverage]=useState<Coverage|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null),[queue,setQueue]=useState<Queue|null>(null),[resources,setResources]=useState<Resource[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]);
 const [allocationQty,setAllocationQty]=useState<Record<number,string>>({}),[selected,setSelected]=useState<Report|null>(null),[intake,setIntake]=useState({report_type:'relief',category:'food',description:'',location:'',people_affected:'',required_quantity:'',evidence_status:'none',evidence_source:'report text',evidence_note:''}),[evidence,setEvidence]=useState<Evidence|null>(null),[evidenceReviewed,setEvidenceReviewed]=useState(false),[verified,setVerified]=useState(''),[verifiedUnit,setVerifiedUnit]=useState('packets'),[delivery,setDelivery]=useState<Record<number,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [a,b,c,d,e,f,g]=await Promise.all([fetch(API+'/reports'),fetch(API+'/relationships'),fetch(API+'/coverage'),fetch(API+'/dashboard'),fetch(API+'/reconciliation/queue'),fetch(API+'/resources'),fetch(API+'/allocations')]);if([a,b,c,d,e,f,g].some((x:Response)=>!x.ok))throw Error('Backend request failed');setReports(await a.json());setRels(await b.json());setCoverage(await c.json());setDashboard(await d.json());setQueue(await e.json());setResources(await f.json());setAllocations(await g.json());setError('')}catch(e){setError(e instanceof Error?e.message:'Backend unavailable')}};
 useEffect(()=>{load()},[]);
 const review=async(r:Report)=>{setSelected(r);setEvidence(null);setEvidenceReviewed(false);setVerified('');setVerifiedUnit(r.category==='food'?'packets':'units');try{const x=await fetch(API+`/reports/${r.id}/evidence`);if(!x.ok)throw Error('Evidence review failed');setEvidence(await x.json());setError('')}catch(e){setError(e instanceof Error?e.message:'Evidence review failed')}};
 const markEvidenceReviewed=async()=>{if(!selected)return;setBusy(true);try{const r=await fetch(API+`/reports/${selected.id}/evidence/review`,{method:'POST'});if(!r.ok)throw Error('Evidence review could not be recorded');setEvidenceReviewed(true);await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Evidence review failed')}finally{setBusy(false)}};
 const createReport=async()=>{setBusy(true);try{const payload={...intake,people_affected:Number(intake.people_affected||0),required_quantity:Number(intake.required_quantity||0)};const r=await fetch(API+'/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error((await r.json()).detail||'Report creation failed');setIntake({report_type:'relief',category:'food',description:'',location:'',people_affected:'',required_quantity:'',evidence_status:'none',evidence_source:'report text',evidence_note:''});await load();setError('Synthetic report created. It remains unverified until responder review.')}catch(e){setError(e instanceof Error?e.message:'Report creation failed')}finally{setBusy(false)}};
 const related=(id:number)=>rels.filter(x=>x.report_a_id===id||x.report_b_id===id);
 const decide=async(id:number,decision:string)=>{setBusy(true);try{const r=await fetch(API+`/relationships/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});if(!r.ok)throw Error((await r.json()).detail||'Decision failed');await load()}catch(e){setError(e instanceof Error?e.message:'Decision failed')}finally{setBusy(false)}};
 const allocate=async(nid:number,rid:number)=>{const q=Number(allocationQty[nid]||'');if(!Number.isFinite(q)||q<=0){setError('Enter an allocation quantity greater than 0');return}setBusy(true);try{const r=await fetch(API+'/allocations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({need_id:nid,resource_id:rid,allocated_quantity:q})});if(!r.ok)throw Error((await r.json()).detail||'Allocation failed');setAllocationQty(prev=>({...prev,[nid]:''}));await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Allocation failed')}finally{setBusy(false)}};
 const createNeed=async()=>{if(!selected)return;if(!evidenceReviewed){setError('Mark evidence reviewed before creating a verified need');return}const q=Number(verified);if(!Number.isFinite(q)||q<=0){setError('Enter a verified quantity greater than 0');return}setBusy(true);try{const r=await fetch(API+'/needs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report_id:selected.id,verified_quantity:q,unit:verifiedUnit.trim()})});if(!r.ok)throw Error((await r.json()).detail||'Verification failed');setVerified('');await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Verification failed')}finally{setBusy(false)}};
 const recordDelivery=async(nid:number, aid?:number)=>{const q=Number(delivery[aid ? `${nid}-${aid}` : nid]||'');if(!Number.isFinite(q)||q<=0){setError('Enter a delivery quantity greater than 0');return}setBusy(true);try{const r=await fetch(API+'/deliveries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({need_id:nid,delivered_quantity:q,allocation_id:aid})});if(!r.ok)throw Error((await r.json()).detail||'Delivery failed');setDelivery(prev=>({...prev,[aid ? `${nid}-${aid}` : nid]:''}));await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Delivery failed')}finally{setBusy(false)}};
 return <main><header><div><h1>CrisisRoute</h1><span>Synthetic demo • Human-in-the-loop</span></div><div className="badge">Evidence is context, not proof</div></header>{error&&<div className="error">{error}</div>}
 <section><h2>Responder overview</h2>{!dashboard?<p>Loading dashboard…</p>:<div className="summary"><div><b>{dashboard.unverified_report_count}</b><small>Unverified reports</small></div><div><b>{dashboard.pending_relationship_count}</b><small>Unresolved relationships</small></div><div><b>{dashboard.uncovered_need_count}</b><small>Needs with gaps</small></div><div><b>{dashboard.verified_need_count}</b><small>Verified needs</small></div></div>}</section><section><h2>Reconciliation queue</h2>{!queue?<p>Loading reconciliation queue…</p>:queue.items.length===0?<p>No unresolved relationships need review.</p>:<div>{queue.items.map(item=><article key={item.relationship_id}><div><h3>Relationship #{item.relationship_id} — {item.relationship_type.replace('_',' ')}</h3><p>{item.reason} · similarity {item.similarity}</p><p className="guardrail">{item.decision_guidance}</p><div className="comparison"><div><b>Report #{item.report_a.id}</b><p>{item.report_a.description}</p><small>{item.report_a.report_type} · {item.report_a.category} · {item.report_a.location}</small><small>People: {item.report_a.people_affected} · Requested: {item.report_a.required_quantity}</small><small>Verification: {item.report_a.verification_status}</small><small>Evidence: {item.report_a.evidence.status} · {item.report_a.evidence.freshness}</small><small>Source: {item.report_a.evidence.source}</small><small>Observed: {item.report_a.evidence.observed_at||'Not provided'}</small><small>Note: {item.report_a.evidence.note||'None'}</small></div><div><b>Report #{item.report_b.id}</b><p>{item.report_b.description}</p><small>{item.report_b.report_type} · {item.report_b.category} · {item.report_b.location}</small><small>People: {item.report_b.people_affected} · Requested: {item.report_b.required_quantity}</small><small>Verification: {item.report_b.verification_status}</small><small>Evidence: {item.report_b.evidence.status} · {item.report_b.evidence.freshness}</small><small>Source: {item.report_b.evidence.source}</small><small>Observed: {item.report_b.evidence.observed_at||'Not provided'}</small><small>Note: {item.report_b.evidence.note||'None'}</small></div></div></div><div className="delivery"><button disabled={busy} onClick={()=>decide(item.relationship_id,'accept')}>Accept</button><button disabled={busy} onClick={()=>decide(item.relationship_id,'reject')}>Reject</button><button disabled={busy} onClick={()=>{const r=reports.find(x=>x.id===item.report_a.id);if(r)review(r)}}>Open report review</button></div></article>)}</div>}</section>
 <section><h2>Report intake</h2><p className="guardrail">Synthetic/demo intake only. New reports start unverified and require human review.</p><div className="intake"><select value={intake.report_type} onChange={e=>setIntake({...intake,report_type:e.target.value})}><option value="relief">Relief</option><option value="emergency">Emergency</option></select><input placeholder="Category" value={intake.category} onChange={e=>setIntake({...intake,category:e.target.value})}/><input placeholder="Location" value={intake.location} onChange={e=>setIntake({...intake,location:e.target.value})}/><input type="number" min="0" placeholder="People affected" value={intake.people_affected} onChange={e=>setIntake({...intake,people_affected:e.target.value})}/><input type="number" min="0" step="1" placeholder={intake.report_type==='relief'?'Required quantity':'Required quantity (0 for emergency)'} value={intake.required_quantity} onChange={e=>setIntake({...intake,required_quantity:e.target.value})}/><textarea placeholder="Description" value={intake.description} onChange={e=>setIntake({...intake,description:e.target.value})}/><select value={intake.evidence_status} onChange={e=>setIntake({...intake,evidence_status:e.target.value})}><option value="none">No supporting evidence</option><option value="photo">Photo</option><option value="document">Document</option><option value="other">Other</option></select><input placeholder="Evidence source" value={intake.evidence_source} onChange={e=>setIntake({...intake,evidence_source:e.target.value})}/><textarea placeholder="Evidence note (optional)" value={intake.evidence_note} onChange={e=>setIntake({...intake,evidence_note:e.target.value})}/><button disabled={busy} onClick={createReport}>Create synthetic report</button></div></section>
<section><h2>Reports & reconciliation</h2>{reports.map(r=><article key={r.id}><div><h3>Report #{r.id} — {r.category}</h3><p>{r.description}</p><p>{r.location} · {r.people_affected} affected · Requested {r.required_quantity}</p><p>Evidence: <b>{r.evidence_status}</b> · Verification: {r.verification_status} · <b>{r.is_synthetic?'Synthetic demo':'External'}</b></p></div><button onClick={()=>review(r)}>Review report</button></article>)}</section>
 <section><h2>Recent activity</h2>{!dashboard||dashboard.recent_audit.length===0?<p>No responder actions recorded yet.</p>:<div>{dashboard.recent_audit.slice(0,8).map(a=><article key={a.id}><div><b>{a.event_type.replaceAll("_"," ")}</b><p>{a.summary}</p><small>{new Date(a.created_at).toLocaleString()}</small></div></article>)}</div>}</section><section><h2>Operational resources</h2><p className="guardrail">Synthetic/demo inventory only. Allocation reserves available stock for a verified need; allocation is not delivery.</p>{resources.length===0?<p>No resources available.</p>:resources.map(r=><article key={r.id}><div><h3>Resource #{r.id} — {r.name}</h3><p>{r.resource_type} · {r.location} · {r.unit}</p><p>Available: <b>{r.available_quantity}</b> · Reserved/allocated: {r.allocated_quantity} · Status: {r.status} · {r.is_synthetic?'Synthetic demo':'External'}</p><small>Source: {r.source}</small></div></article>)}</section>
<section><h2>Need allocations</h2>{!coverage||coverage.needs.length===0?<p>No verified needs to allocate.</p>:coverage.needs.map(n=><article key={n.need_id}><div><h3>Need #{n.need_id}</h3><p>Verified {n.verified_quantity} {n.unit} · Allocated {n.allocated_quantity} · Remaining to allocate {n.remaining_to_allocate} · Delivered {n.delivered_quantity} · Uncovered {n.uncovered_quantity}</p><div className="delivery"><input type="number" min="0" step="1" placeholder="Allocation" value={allocationQty[n.need_id]||''} onChange={e=>setAllocationQty(prev=>({...prev,[n.need_id]:e.target.value}))}/>{resources.filter(r=>r.status==='active' && r.unit.toLowerCase()===n.unit.toLowerCase() && r.available_quantity>0).map(r=><button key={r.id} disabled={busy||n.remaining_to_allocate<=0} onClick={()=>allocate(n.need_id,r.id)}>Allocate from {r.name}</button>)}</div></div></article>)}</section>
<section><h2>Allocation records</h2>{allocations.length===0?<p>No allocations recorded yet.</p>:allocations.map(a=><article key={a.id}><div><h3>Allocation #{a.id}</h3><p>Need #{a.need_id} · Resource #{a.resource_id} · Allocated {a.allocated_quantity} · Delivered {a.delivered_quantity} · Remaining {a.remaining_quantity}</p><div className="delivery"><input type="number" min="0" step="1" placeholder="Delivery" value={delivery[`${a.need_id}-${a.id}`]||''} onChange={e=>setDelivery(prev=>({...prev,[`${a.need_id}-${a.id}`]:e.target.value}))}/><button disabled={busy} onClick={()=>recordDelivery(a.need_id, a.id)}>Record allocated delivery</button></div></div></article>)}</section>
<section><h2>Relief coverage</h2>{!coverage?<p>Loading coverage…</p>:<><div className="summary"><div><b>{coverage.total_verified}</b><small>Verified required</small></div><div><b>{coverage.total_delivered}</b><small>Delivered</small></div><div><b>{coverage.total_uncovered}</b><small>Uncovered</small></div></div>{coverage.needs.length===0?<p>No verified needs yet.</p>:coverage.needs.map(n=><article key={n.need_id}><div><h3>Need #{n.need_id}</h3><p>Report #{n.report_id} · Verified {n.verified_quantity} {n.unit} · Allocated {n.allocated_quantity} · Delivered {n.delivered_quantity} · Uncovered {n.uncovered_quantity}</p><progress max="100" value={n.coverage_percent}/><p>{n.coverage_percent}% covered</p></div><div className="delivery"><input type="number" min="0" step="1" placeholder="Delivery" value={delivery[n.need_id]||''} onChange={e=>setDelivery(prev=>({...prev,[n.need_id]:e.target.value}))}/><button disabled={busy} onClick={()=>recordDelivery(n.need_id)}>Record delivery</button></div></article>)}</>}</section>
 {selected&&<aside><div className="drawer"><button className="close" onClick={()=>setSelected(null)}>Close</button><h2>Report #{selected.id}</h2><p>{selected.description}</p><p><b>Location:</b> {selected.location}</p><p><b>People affected:</b> {selected.people_affected}</p><p><b>Requested:</b> {selected.required_quantity}</p><h3>Evidence review</h3>{evidence?<><p><b>Status:</b> {evidence.evidence_status}</p><p><b>Source:</b> {evidence.evidence_source}</p><p><b>Observed:</b> {evidence.observed_at||'Not provided'}</p><p><b>Freshness:</b> {evidence.freshness}</p><p><b>Note:</b> {evidence.evidence_note||'None'}</p><p><b>Human review:</b> {evidenceReviewed?'Recorded':'Required'}</p><p className="guardrail">Evidence must be explicitly reviewed before a verified need can be created.</p><button disabled={busy||evidenceReviewed} onClick={markEvidenceReviewed}>{evidenceReviewed?'Evidence review recorded':'Mark evidence reviewed'}</button></>:<p>Loading evidence…</p>}
 <h3>Related reports</h3>{related(selected.id).length===0?<p>No suggested relationships.</p>:related(selected.id).map(x=><div className="rel" key={x.id}><b>{x.relationship_type.replace('_',' ')}</b><p>{x.reason} · similarity {x.similarity}</p><p>Decision: {x.decision}</p><button disabled={busy} onClick={()=>decide(x.id,'accept')}>Accept</button><button disabled={busy} onClick={()=>decide(x.id,'reject')}>Reject</button><button disabled={busy} onClick={()=>decide(x.id,'unresolved')}>Unresolved</button></div>)}
 {selected.report_type==='relief'&&<><h3>Human verification</h3><div className="delivery"><input placeholder="Unit (e.g. packets)" value={verifiedUnit} onChange={e=>setVerifiedUnit(e.target.value)}/><input type="number" min="0" step="1" placeholder="Verified quantity" value={verified} onChange={e=>setVerified(e.target.value)}/><button disabled={busy||!evidenceReviewed} onClick={createNeed}>Create verified need</button></div></>}
 <p className="guardrail">Final verification and operational decisions remain with the human responder.</p></div></aside>}
 </main>}
createRoot(document.getElementById('root')!).render(<App/>);
